class_name IRCMessageTypes

const MODE_MESSAGE = "MODE"

const NOTICE_MESSAGE = "NOTICE"

const PING_MESSAGE = "PING"

const PONG_MESSAGE = "PONG"

const PRIVMSG_MESSAGE = "PRIVMSG"

const RPL_WELCOME = "001"

const RPL_YOURHOST = "002"

const RPL_CREATED = "003"

const RPL_MYINFO = "004"

const RPL_BOUNCE = "005"

const RPL_LUSERCLIENT = "251"

const RPL_LUSEROP = "252"

const RPL_LUSERUNKNOWN = "253"

const RPL_LUSERCHANNELS = "254"

const RPL_LUSERME = "255"

const RPL_LOCALUSERS = "265"

const RPL_GLOBALUSERS = "266"

const RPL_CHANNELMODEIS = "324"

const RPL_CREATIONTIME = "329"

const RPL_NOTOPIC = "331"

const RPL_TOPIC = "332"

const RPL_MOTDSTART = "375"

const RPL_MOTD = "372"

const RPL_ENDOFMOTD = "376"

const ERR_NEEDMOREPARAMS = "461"
